### ISSUE TITLE
preprint or published bibcode duplication can lead to oracle 400s due to bulk_insert

### ISSUE THREAD

**Issue by seasidesparrow** [adsabs/oracle_service#73]
There may be circumstances where we want to submit a file of preprint-published matches where one or both bibcodes are a duplicate; this is especially true of incorrect bibcodes where there may be (for example) multiple conference proceedings that closely match a given preprint.

The specific case we have with docmatch_pipeline is the case of trying to load a file like `abstracts/sources/ArXiv/pub/matches.kill` where we may kill multiple incorrect matches at once.  If both of these records are in the same file, and are in the same batch of nmax records, the postgres bulk_insert will fail and the service will return a 400.

**Comment by ehenneken** [comment]
@golnazads Is this sufficient information?

**Comment by golnazads** [comment]
I dont have the full path to see the file, went the usual route of 
ls /proj/ads/abstracts/sources/ArXiv/pub/matches.kill
ls: cannot access /proj/ads/abstracts/sources/ArXiv/pub/matches.kill: No such file or directory

@ehenneken @seasidesparrow

**Comment by golnazads** [comment]
But just going by description, yes bulk_insert fails if there are multiple records. And to save time, we need to use bulk_insert. My suggestion is to submit one file at a time, the pipeline is created to process one input file at a time.

@ehenneken @seasidesparrow

**Comment by ehenneken** [comment]
@golnazads Actually, the correct path is `/proj/ads/abstracts/sources/ArXiv/published/matches.kill`

**Comment by golnazads** [comment]
@ehenneken this is a large file. And as you know, inserting to database even bulk insert takes some time, that with the network layers, and the time limit to process and return from a service, the best approach is to submit the correction for one file at a time. Do not combine.

**Comment by golnazads** [comment]
Created this issue in docmatching repo https://github.com/adsabs/ADSDocMatchPipeline/issues/40
@ehenneken @seasidesparrow @aaccomazzi
